src/Entity/Recette.php
<?php

namespace App\Entity;

use App\Repository\RecetteRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecetteRepository::class)]
class Recette
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(nullable: true)]
    private ?bool $est_favori = null;

    #[ORM\Column]
    private ?int $quantite1 = null;

    #[ORM\Column]
    private ?int $quantite2 = null;

    #[ORM\Column]
    private ?int $quantite3 = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ingredient1 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ingredient2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $ingredient3 = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function isEstFavori(): ?bool
    {
        return $this->est_favori;
    }

    public function setEstFavori(?bool $est_favori): self
    {
        $this->est_favori = $est_favori;

        return $this;
    }

    public function getQuantite1(): ?int
    {
        return $this->quantite1;
    }

    public function setQuantite1(int $quantite1): self
    {
        $this->quantite1 = $quantite1;

        return $this;
    }

    public function getQuantite2(): ?int
    {
        return $this->quantite2;
    }

    public function setQuantite2(int $quantite2): self
    {
        $this->quantite2 = $quantite2;

        return $this;
    }

    public function getQuantite3(): ?int
    {
        return $this->quantite3;
    }

    public function setQuantite3(int $quantite3): self
    {
        $this->quantite3 = $quantite3;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIngredient1(): ?string
    {
        return $this->ingredient1;
    }

    public function setIngredient1(?string $ingredient1): self
    {
        $this->ingredient1 = $ingredient1;

        return $this;
    }

    public function getIngredient2(): ?string
    {
        return $this->ingredient2;
    }

    public function setIngredient2(?string $ingredient2): self
    {
        $this->ingredient2 = $ingredient2;

        return $this;
    }

    public function getIngredient3(): ?string
    {
        return $this->ingredient3;
    }

    public function setIngredient3(?string $ingredient3): self
    {
        $this->ingredient3 = $ingredient3;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
}

src/Controller/ListeController.php
<?php

namespace App\Controller;

use App\Entity\Recette;
use App\Form\RecetteType;
use App\Repository\RecetteRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ListeController extends AbstractController
{
    #[Route('/liste', name: 'app_liste')]
    public function index(RecetteRepository $recetteRepository, EntityManagerInterface $em): Response
    {
        $recette = $recetteRepository->lister();
        dump($recette);
        return $this->render('liste/index.html.twig', [
            'controller_name' => 'ListeController',
            'listeRecettes' => $recette
        ]);
    }

    #[Route('/modifFavori/{id}', name: 'app_modif_fav')]
    public function ModifFav(RecetteRepository $recetteRepository,$id,EntityManagerInterface $entityManager, Request $request): Response
    {
        $recette = $recetteRepository->find($id);
       $recette->setEstFavori(!$recette->isEstFavori());
       $entityManager->persist($recette);
       $entityManager->flush();
       $cookies = $request->cookies;
       if($cookies->get('tri') == 'nom'){
           return $this->redirectToRoute('app_tri_nom');
        }else{
           return $this->redirectToRoute('app_tri_favoris');
       }

    }

    #[Route('/triParNom', name: 'app_tri_nom')]
    public function triNom(RecetteRepository $recetteRepository): Response
    {
        $val = 'nom';
        $response = new Response();
        $response->headers->setCookie(new Cookie('tri', $val,time() + (365 * 24 * 60 * 60)));
        $response->send();

        $liste = $recetteRepository ->findBy([],['nom'=>'ASC']);
        return $this->render('liste/index.html.twig', [
            'controller_name' => 'ListeController',
            'listeRecettes' => $liste
        ]);
    }

    #[Route('/triParFavoris', name: 'app_tri_favoris')]
    public function triFavoris(RecetteRepository $recetteRepository): Response
    {
        $val = 'favoris';
        $response = new Response();
        $response->headers->setCookie(new Cookie('tri', $val,time() + (365 * 24 * 60 * 60)));
        $response->send();


        $liste = $recetteRepository ->findBy([],['est_favori'=>'ASC']);
        return $this->render('liste/index.html.twig', [
            'controller_name' => 'ListeController',
            'listeRecettes' => $liste
        ]);
    }




}

templates/liste/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de mes recettes{% endblock %}

{% block body %}
    <nav>
        <ul class="ul_nav">
            <li><a href="{{ path('app_accueil') }}">Accueil</a></li>
            <li>Liste</li>
        </ul>
    </nav>
    <main>
        <div class="triRecettes">
            <button><a class="button_text" href="{{ path('app_tri_favoris') }}">Trier par favoris</a></button>
            <button><a class="button_text" href="{{ path('app_tri_nom') }}">Trier par nom</a></button>
            <button><a class="button_text" href="{{ path('app_form') }}">Créer recette</a></button>
        </div>
        <div class="liste">
            {% for element in listeRecettes %}
                <div class="recette">
                    <a class="container-Recette" href="{{path('app_details',{'id':element.id})}}">
                        <div class="titre">
                            <h3 class="titre_recette">{{ element.nom }}</h3>
                            <a class="lien_etoile" href="{{path('app_modif_fav',{'id':element.id})}}">
                                <svg class="test" xmlns="http://www.w3.org/2000/svg" version="1.0" width="1280.000000pt" height="1216.000000pt" viewBox="0 0 1280.000000 1216.000000" preserveAspectRatio="xMidYMid meet">
                                    <g transform="translate(0.000000,1216.000000) scale(0.100000,-0.100000)" {% if element.estFavori == 0 %} fill='#fcd21c' {% else %} fill='#E1DDCD' {% endif %} stroke="none">
                                        <path d="M5890 10598 c-332 -755 -736 -1674 -898 -2043 -161 -368 -295 -671 -297 -673 -2 -2 -308 -25 -682 -52 -373 -27 -1054 -76 -1513 -109 -459 -34 -1087 -79 -1395 -101 -308 -22 -585 -43 -615 -46 l-54 -6 49 -47 c28 -25 336 -300 684 -611 349 -311 806 -718 1016 -905 1267 -1130 1560 -1391 1572 -1400 17 -13 74 228 -542 -2265 -256 -1036 -464 -1887 -463 -1890 2 -4 869 499 1928 1117 1058 618 1931 1122 1940 1120 8 -2 398 -242 865 -532 468 -291 1165 -724 1550 -963 385 -239 811 -504 947 -588 135 -85 249 -154 253 -154 4 0 4 17 0 38 -6 34 -411 1897 -776 3568 -87 402 -159 738 -159 747 0 13 649 563 2997 2542 258 217 261 220 230 227 -18 4 -1011 104 -2207 223 -1196 119 -2184 220 -2196 225 -15 6 -62 111 -199 446 -98 242 -412 1013 -697 1714 -285 701 -564 1388 -620 1525 -56 138 -104 253 -108 258 -3 4 -278 -610 -610 -1365z"/>
                                    </g>
                                </svg>
                            </a>
                        </div>
                        <a href="{{path('app_details',{'id':element.id})}}"><img class="image_recette" src="{{ asset('images/'~element.image)}}" width="200"></a>
                    </a>
                </div>
            {%endfor%}
        </div>
    </main>
{% endblock %}